### ISSUE TITLE
Honkbot improvements

### ISSUE THREAD

**Issue by Pyko1** [HippieStation/HippieStation13#150]
Make it also report controller crashes/restarts to #server-announcements

**Comment by Pyko1** [comment]
Also more round end detail.
Ie.
2 Traitors were successful.
Nuclear Operatives Won won.
etc.

**Comment by Pyko1** [comment]
Maybe even:

A round of Wizard ended has ended - 14 survivors, 15 ghosts.
Random event meteors were triggered at 20 minutes.
Wizard died at 28 minutes, round was mullgian changed to traitors.
Random event aliens were triggered 45 minutes.
Round end time 52 minutes.

**Comment by Pyko1** [comment]
Also honk at coderchat on new github comments.

**Comment by Pyko1** [comment]
Turn the IP in to an actual join link on
`Server starting up on byond://178.32.113.205:3000. Map is Box Station`

**Comment by Chnkr** [comment]
Please open these in the honkbot repository
