### ISSUE TITLE
[Blood] -O

### ISSUE THREAD

**Issue by Swagile** [HippieStation/HippieStation13#156]
A player ahelped about dying from toxins after filling himself with -O blood (which should be universal). I assume this is a bug or something with the rebase / special species. No idea why it happened, I just know he died from toxins pretty quick.

**Comment by JamieH** [comment]
What species was he?

**Comment by tortellinitony** [comment]
I don't think blood type L can get O-

**Comment by WallaceShark** [comment]
Flyman. No toxin damage, just mass oxy damage.

**Comment by JamieH** [comment]
@WallaceShark What blood type were you?

**Comment by tortellinitony** [comment]
I'm going to close this because it does not appear to be an issue.
