### ISSUE TITLE
Can fart and scream while dead

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStation13#17]
Clearly intended

**Comment by blobbernaut** [comment]
It's just the body settling and decomposing

**Comment by McBawbaggings** [comment]
ayy fucking lmao

**Comment by McBawbaggings** [comment]
I'm assuming this is hotkey only??

**Comment by JamieH** [comment]
Yeah

**Comment by Alphora** [comment]
Lol, I've no problem with this. Bodies fart. Maybe no screaming.

**Comment by tortellinitony** [comment]
this is fixed
