### ISSUE TITLE
SOMETHING to do with Mindbreaker Toxin crashes Dreamseeker.

### ISSUE THREAD

**Issue by PopNotes** [HippieStation/HippieStation13#181]
I don't know exactly what causes this. If nobody else can be fucked, I'll try to do some testing on my own server to see what it is. All I know so far is A. It's caused by hallucinations/mindbreaker and B. It's not instant, nor is it on a fixed delay. Speculation here, I'm pretty sure it's caused by a specific hallucination that somehow crashes dreamseeker.

**Comment by JamieH** [comment]
Maybe we shouldn't put this on our public bug tracker? Just maybe???

**Comment by JamieH** [comment]
Couldn't replicate after 5 minutes of hallucinating

**Comment by JamieH** [comment]
Rejoining seems to fix it.

**Comment by JamieH** [comment]
Related to
https://github.com/tgstation/tgstation/issues/19747 
https://github.com/tgstation/tgstation/issues/23338
https://github.com/tgstation/tgstation/issues/22565

**Comment by JamieH** [comment]
I suggest putting a
```
world.log << hal_type
```

https://github.com/HippieStation/HippieStation13/blob/42915e2f0fc726df31f1cebd7f3206907862c391/code/modules/flufftext/Hallucination.dm#L550 and seeing which one is causing it.

**Comment by tortellinitony** [comment]
All hallucinations seem to be causing this issue on some users' clients.
