### ISSUE TITLE
Grab level indicators in hand slot.

### ISSUE THREAD

**Issue by ZachDeava** [HippieStation/HippieStation13#21]
According to the Trello this wasn't ported yet.

**Comment by tortellinitony** [comment]
the grab indicator is separate

**Comment by tortellinitony** [comment]
This probably won't happen because you can have an item in your hand while you grab, and there can't be an indicator there.

**Comment by ZachDeava** [comment]
That's fine then. Was just moving concrete items to GitHub since we're not going to use Trello anymore.
