### ISSUE TITLE
OOCbans ban you from deadchat too

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#341]
MAKE A DEADCHAT BAN IF YOU FEEL SO STRONGLY ABOUT IT

**Comment by tortellinitony** [comment]
uh oh did you get ooc banned?

**Comment by KittyKathy** [comment]
Yes he did for 1 day, still a bug though I guess or is it?

**Comment by cacogen** [comment]
they're both out of character channels, so
