### ISSUE TITLE
Changelings can't regenerate their limbs

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#362]
Lost a round because of this bullshit, fuck /tg/, why did we even rebase if we get so many of these issues? Hell, I think theres more issues now than there have ever been.

**Comment by JohnGinnane** [comment]
Might need to expand on https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/modules/mob/living/living.dm#L449 but this should be present on /tg/ as well?

**Comment by cacogen** [comment]
being a decapitated changeling and regenerating without a head and then running around headless is one of life's simpler pleasures

though i couldn't understand how it worked, i thought my mind was in the brain in the head on the floor

**Comment by JohnMcLaime** [comment]
They can regen limbs by using separate ability, it a stock one though, called "regenerate". Instant and low cost.

**Comment by ArcLumin** [comment]
No arms no legs no head somehow still crawl around

**Comment by tortellinitony** [comment]
/obj/effect/proc_holder/changeling/regenerate
	name = "Regenerate"
	desc = "Allows us to regrow and restore missing external limbs, and \
		vital internal organs, as well as removing shrapnel and restoring \
		blood volume."
