### ISSUE TITLE
this shuttle looks like shit

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#363]
notices ur bulge lmao wtf it looks retarded

![](https://vgy.me/uJHPDo.png)

**Comment by JohnGinnane** [comment]
Not really an issue..

**Comment by JohnGinnane** [comment]
If you want to fix it, go ahead))

**Comment by cacogen** [comment]
the airlocks not lining up is worse

the bulges look like they tried to give it some character so it wasn't just a plain rectangular shape but ended up making it look like shit instead

**Comment by Chnkr** [comment]
its a meme shuttle
