### ISSUE TITLE
DUCT TAPE AND MAKESHIFT ARMOR ARE GONE

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#364]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by GuyonBroadway** [comment]
WE RE ADDED DUCT TAPE YOU MISERABLE GALACTIC PENIS

**Comment by JohnGinnane** [comment]
![screenshot_20170227-081105](https://cloud.githubusercontent.com/assets/3355198/23353460/7b899368-fcc4-11e6-962b-da1224bc911e.png)

**Comment by JohnGinnane** [comment]
They're there, just not as common apparently
