### ISSUE TITLE
even if you're in the maintenance tunnels shielded from radiation storms, the game will still warn you

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#370]
You feel waves of heat wash over you! Find shelter!

but I WAS IN MAINTENANCE HOW WOULD I FEEL THE RADIATION

**Comment by ArcLumin** [comment]
You can still feel radiation without taking rads my dude.

**Comment by Spacedong** [comment]
fuck you

**Comment by ArcLumin** [comment]
fuck you leatherman

**Comment by ArcLumin** [comment]
also not an issue my dude

**Comment by ArcLumin** [comment]
space "how can I feel heat without burning" dong
