### ISSUE TITLE
tesla NEVER FUCKS OFF TO SPACE EVER 

### ISSUE THREAD

**Issue by blobbernaut** [HippieStation/HippieStation13#495]
jesus fuck help

**Comment by banthebantz** [comment]
it's gay

**Comment by cacogen** [comment]
impremove

**Comment by yobob591** [comment]
Tesla is actually attracted to metal tiles/machines. Station is literally made of mostly metal. Yeah

**Comment by JohnGinnane** [comment]
Gonna close this as I've seen first hand the tesla roaming off into space for a while, before eventually coming back and spending a copious amount of time near solars
