### ISSUE TITLE
names in screams get duplicated

### ISSUE THREAD

**Issue by Spacedong** [HippieStation/HippieStation13#56]
For example instead of "Dan K. Memes screams!" it will be displayed as "Dan K. Memes Dan K. Memes screams!"

**Comment by tortellinitony** [comment]
try deleting the message = "screams" and message mime = "acts out a scream" lines in the file, compile it and test it, and see if it fixes the issue

**Comment by tortellinitony** [comment]
at the top, may I add, under the emote and not the run emote bit

**Comment by Spacedong** [comment]
k

**Comment by tortellinitony** [comment]
fixed
