### ISSUE TITLE
You don't go to Hell after dying after selling your soul

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStation/HippieStation13#70]
You're supposed to not be able to ghost, stuck in a black box in a small room for the rest of the round. You're able to ghost.

**Comment by Sarcalogo** [comment]
Woops looks like /tg/ reverted that, the pussies. I'd suggest re-adding it but whatev

**Comment by yobob591** [comment]
I agree that this would give a reason not to sell your soul
